swagger: '2.0'
info:
  description: Open EMR Blockchain API Endpoint to store and retreive data from State
  version: 1.0.0
  title: Open EMR Blockchain API
  # put the contact info for your development or API team
  contact:
    email: johnjayasingh.s@gmail.com

# tags are used for organizing operations
tags:
- name: patient
  description: Patient related api

paths:
  /patient:
    get:
      tags: 
      - patient
      summary: Create Patient to state
      description: Add patient entry to state
      parameters:
      - name: "id"
        in: "query"
        description: "Patient ID should be passed"
        type: "string"
      responses:
        200:
          description: Patient Details Retreived
        400:
          description: invalid input, query params invalid
    post:
      tags:
      - patient
      summary: Create Patient to state
      description: Add patient entry to state
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: patientItem
        description: Patient item to add
        schema:
          $ref: '#/definitions/CreatePatient'
      responses:
        201:
          description: Patient ID created
        400:
          description: invalid input, object invalid
  /patient/{id}
    delete:
      tags:
      - patient
      summary: Delete Patient from state
      description: Delete Patient entry from blockchain state
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        schema: 
          type: string
        required: true
        description: ID of the patient to be deleted
    update:
      tags:
      - patient
      summary: Updates patient records
      description: Update patient record
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        schema:
          type: string
          required: true
          description: ID of the patient to be updated in state
      - in: body
        name
definitions:
  CreatePatient:
    type: object
    properties:
      id:
        type: string
        example: P1
      document:
        type: array
        items: 
          type: string
          example: http://unec.edu.az/application/uploads/2014/12/pdf-sample.pdf
# Added by API Auto Mocking Plugin
host: 13.251.142.80:3000
basePath: /api
schemes:
 - http