version: '3.0'

services:
  sawtooth-client:
    container_name: sawtooth-client
    environment:
      - 'HOST=18.136.137.49:3000'
    command: npm run start-dev
  rest-api-proxy:
    container_name: sawtooth-explorer-rest-api-proxy
    volumes:
      - ./nginx-dev.conf:/etc/nginx/nginx.conf:ro