version: '3.0'

services:
  sawtooth-client:
    container_name: sawtooth-client
    environment:
      - 'HOST=localhost:3000'
    command: npm run start-local
  rest-api-proxy:
    container_name: sawtooth-explorer-rest-api-proxy
    volumes:
      - ./nginx-local.conf:/etc/nginx/nginx.conf:ro