version: '2.0'

services:
  openemr-processor:
    container_name: openemr-processor
    build:
      context: .
      dockerfile: ./contract/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - 'VALIDATOR_URL=tcp://validator:4004'
    depends_on:
      - validator
    # volumes:
      # - './contract:/usr/src/app'

  sawtooth-client:
    container_name: sawtooth-client
    build:
      context: .
      dockerfile: ./explorer/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    command: |
          npm run start-dev
    # volumes: 
    #   - './keys:/root/.sawtooth/keys/'
    environment:
      - 'REST_API=http://rest-api:8008'
      - 'NODE_ENV=${NODE_ENV}'
    # volumes:
      # - './explorer:/usr/src/app'
    ports:
      - '0.0.0.0:3000:3000'
    depends_on:
      - sawtooth-rest-api
      - openemr-processor
    stop_signal: SIGKILL
  openemr-api-swagger:
    container_name: openemr-api-swagger
    build:
      context: .
      dockerfile: ./swagger/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - 'HOST=${HOST}'
    # volumes:
      # - './swagger:/usr/src/app'
    depends_on: 
      - 'sawtooth-client'
    ports:
      - '0.0.0.0:3001:3001'
    stop_signal: SIGKILL

  sawtooth-rest-api:
    container_name: rest-api
    image: hyperledger/sawtooth-rest-api:1.0
    expose:
      - 8008
    ports:
      - '8008:8008'
    depends_on:
      - validator
    entrypoint: |
      sawtooth-rest-api -vvv
        --connect tcp://validator:4004
        --bind sawtooth-rest-api:8008

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    depends_on:
      - validator
    command: settings-tp -vv --connect tcp://validator:4004

  validator:
    container_name: validator
    image: hyperledger/sawtooth-validator:1.0
    # environment: 
    #   - 'SAWTOOTH_HOME=/var/'
    # volumes: 
    #  - './data:/var/lib/sawtooth/'
    expose:
      - 4004
    ports:
      - '4004:4004'
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen &&
          sawtooth keygen my_key &&
          sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
          sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator -vvv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800"
  rest-api-proxy:
    image: nginx
    container_name: sawtooth-explorer-rest-api-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8090:8090"
      - "8091:8091"
    command: [nginx, '-g', 'daemon off;']
